feat: Vectorlist std/data/vectorlist
koka-community/std pull request #1
Opened 2024-04-14 00:57 UTC by Ki11erRabbit

I have here a simple vectorlist. A vectorlist is a resizable vector that should have fast lookup times. The name isn't the greatest but it is reminiscent of the Java ArrayList. There are a few functions that are missing but there is enough functionality.

Side note. We might want to write a contributing guideline to keep a general structure for future merges.

2024-04-14 01:59 UTC, TimWhiting commented on std/data/vectorlist.kk
> +fun flatten( item : maybe<maybe<a>> ) : maybe<a>
This should be moved to std/core-extras, (not related to vectorlist but one of those basic things that should be in core)

2024-04-14 02:01 UTC, TimWhiting commented on std/data/vectorlist.kk
> +pub struct vectorlist<a>
Let's call it `vector-list<a>`. I don't necessarily like the way it looks in the constructor, but most people will likely be creating this via some utility like `vlist-empty()` or `vlist/from-list(l: list<a>)`, and we should add an alias as `vlist<a>`.

2024-04-14 02:01 UTC, TimWhiting commented on std/data/vectorlist.kk
> +  pub capacity : int
Curious why capacity is public?

2024-04-14 02:02 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +fun flatten( item : maybe<maybe<a>> ) : maybe<a>
Sure, I'll move it.

2024-04-14 02:02 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +pub struct vectorlist<a>
Consider it done.

2024-04-14 02:04 UTC, TimWhiting commented on std/data/vectorlist.kk
> +    Just(y) -> y
Curious if we can do a simpler copy using some sort of vector `unsafe-index` operation (after all we do know the size of the previous vlist).

2024-04-14 02:05 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +  pub capacity : int
I made it public because the Koka compiler doesn't like it when I write a function that looks the same as an accessor function. That way there is still a function called `capacity` that a user can use to check the capacity.

2024-04-14 02:05 UTC, TimWhiting commented on std/data/vectorlist.kk
> +// Apply a total function `f` to each element in a vectorlist `v`.
This isn't a total function

2024-04-14 02:07 UTC, TimWhiting commented on std/data/vectorlist.kk
> +  var vec := unit/vectorlist()
Take a look at my tests at the end of (https://github.com/koka-community/std/blob/main/std/test/test.kk)

Just have a single test function `test-vlist`, and create subtests within there.

2024-04-14 02:08 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +// Apply a total function `f` to each element in a vectorlist `v`.
I copied most of the descriptions from the Koka stdlib descriptions for the vector as well as function definitions so if there are any errors here, there might be some in the Koka stdlib.

2024-04-14 02:09 UTC, TimWhiting requested changes
Looks pretty good. Have some feedback though. Now that we are contributing to the community, I'd like to start finetuning this, and making the style consistent to koka's standard library.

2024-04-14 03:04 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +    Just(y) -> y
Honestly, I don't think it is that bad. What is bad is how there is no function set in the Koka stdlib for vector so the only option is to create a new vector whenever we want to change an element in a vector.

2024-04-14 03:07 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +fun flatten( item : maybe<maybe<a>> ) : maybe<a>
Moved.

2024-04-14 03:08 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +pub struct vectorlist<a>
I renamed it and added a few aliases.

2024-04-14 03:09 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +  pub capacity : int
changed the name of `capacity` to `vec-length` and made it not public and made a function called `capacity` that accesses `vec-length`

2024-04-14 03:10 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +  var vec := unit/vectorlist()
I have moved my tests to a single function.

2024-04-14 13:57 UTC, TimWhiting commented
The std core vector library uses this definition internally, but doesn't expose it...
```koka
inline extern unsafe-assign : forall<a> ( v : vector<a>, i : ssize_t, x : a ) -> total ()
  c "kk_vector_unsafe_assign"
  cs inline "(#1)[#2] = #3"
  js inline "(#1)[#2] = #3"
```

2024-04-14 14:00 UTC, TimWhiting commented on std/data/vectorlist.kk
> +    Just(y) -> y
The std core vector library uses this definition internally, but doesn't expose it... Obviously only use it when you know the index is not out of bounds.

```
inline extern unsafe-assign : forall<a> ( v : vector<a>, i : ssize_t, x : a ) -> total ()
  c "kk_vector_unsafe_assign"
  cs inline "(#1)[#2] = #3"
  js inline "(#1)[#2] = #3"
```

Try to remove exn from the API again.

2024-04-14 15:24 UTC, TimWhiting commented on std/data/vectorlist.kk
> +    Just(y) -> y
Of course this is a mutating api, so we would need a copy operation for vectors, but I think copy + single mutation should be more performant than the reinitializing with a lambda that checks the index and updates it.

2024-04-14 16:12 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +    Just(y) -> y
Do you know how to access that function? I tried accessing it earlier but I couldn't figure it out.

2024-04-14 16:21 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +    Just(y) -> y
I did some digging and it doesn't appear in the inline folder of koka/lib/std/core, it does however include the code `kk_vector_unsafe_assign` which should allow `vector-list` to not need to recreate its vector when it gets a new element.

2024-04-14 18:11 UTC, Ki11erRabbit commented on std/data/vectorlist.kk
> +    Just(y) -> y
I have now implemented resize with `unsafe-idx`. Let me know if there are any other changes that need to be made.

2024-04-14 23:04 UTC, TimWhiting commented on std/core-extras.kk
> +  c file "inline/core-extras"
You can just specify inline/core_extras.h and get rid of the empty .c file

2024-04-15 00:11 UTC, Ki11erRabbit commented on std/core-extras.kk
> +  c file "inline/core-extras"
I just learned that we don't even need the `C` file and that we can just use the extern function declaration statement. At least that is what my testing shows.

2024-04-15 16:43 UTC, TimWhiting commented on std/core-extras.kk
> +  c file "inline/core-extras"
Yes I was going to say that I think the necessary header files for those definitions are already in the dependencies / imports, but I assumed you had tried / tested it and needed to do this.

2024-04-15 17:03 UTC, TimWhiting commented
@Ki11erRabbit 
I just pushed a commit that optimizes this quite a bit I think. I added a few missing `kk_vector*` apis from the `kklib` headers, as well as added a way of introspecting on the reference count so that we can mutate in place when the reference count is one, and fallback to copying the vector. It seems that using local variables messes up the reference count a bit, so I switched to using `val` in the test. It is kind of hard to test for the difference in behavior if there is a unique reference count or not (since there shouldn't be anything user visible really). So I ended up just making some test cases that "test" it, but really just added some trace statements in the `unique/map` and `unsafe-set` in the `core-extras`.

Also since, the kklib vector implementation uses `kk_box_t`, and there is a unsafe api for initializing with the box equivalent of null, we can omit wrapping everything in `Just` as long as we guarantee the invariant that we don't allow users to access outside of the initialized memory. I think the `maybe` type might be essentially a zero cost wrapper in Koka anyways, but if not than this is an important optimization I think. For popping, we can just change the size, and adjust the ref count of the value.

2024-04-15 17:34 UTC, Ki11erRabbit commented
I just tested pushing 1 million ints into the the vector-list and it failed with the error
`mimalloc: error: corrupted free list entry of size 320b at 0x020000010DC0: value 0xC000020000010C81`

2024-04-15 17:36 UTC, TimWhiting commented
Interesting. I wonder what is wrong. Anyways, let's not feel rushed about getting this api in, let's see if we can get it to a well-documented and really nice state.

2024-04-15 17:38 UTC, Ki11erRabbit commented
I also just threw in a `trace` and it seems to fail after the 9th insertion.

2024-04-15 19:17 UTC, Ki11erRabbit commented
I just discovered something even weirder. If you print out the number being inserted it fails at the 9th insertion but if you don't print out the number being inserted, it fails at a much later insertion with a similar error.

2024-04-15 21:21 UTC, Ki11erRabbit commented
I think I have narrowed down the problem. 
I made a custom unsafe-assign that doesn't internally drop the vector. This causes it to fail on the 9th insertion which would cause a doubling in size.
I also tried removing the copy from `unsafe-set` when the vector isn't unique and it causes a failure much later on.

Both of these lead me to believe that drop is not being called the correct amount of times.

2024-04-15 23:30 UTC, TimWhiting commented
Looks like my borrow annotations on copy / realloc were wrong in `core-extras`. It expects an owned vector.

2024-04-15 23:31 UTC, TimWhiting commented
It might be good to have a few more tests, as well as testing some of the things in core-extras. But maybe we should merge for now.

2024-04-15 23:31 UTC, TimWhiting approved these changes

2024-04-15 23:32 UTC, merged

2024-04-16 04:51 UTC, Ki11erRabbit commented
I just realized that the vector-list doesn't have a clear function for it. What do you think is the best way to clear the vector-list?

2024-04-16 04:58 UTC, TimWhiting commented
Probably best to add a C function that goes from 0 to the sublength of the vector given as a parameter, doing a `kk_box_drop(v, kk_context())` on the values, and setting them to `kk_box_null()`.

2024-04-16 15:08 UTC, Ki11erRabbit commented
I'll do that, thanks.

2024-04-16 21:31 UTC, Ki11erRabbit commented
I have finished making changes to the vector, so it is good to merge in again. @TimWhiting