Vector Deque
koka-community/std pull request #5
Opened 2024-04-21 04:33 UTC by Ki11erRabbit

I have made a double ended queue that is similar to the vector-list. I figured that since Rust's stdlib contained one, I might as well make one for this library.

2024-04-22 15:31 UTC, TimWhiting commented on std/data/deque.kk
> +  Deque( vector-init( n, fn (_) default ), -1, n, n)
So you have -1 as an index here, is it supposed to be that for every empty queue or just for the initial one

2024-04-22 21:19 UTC, TimWhiting commented on std/data/deque.kk
> +  Deque( vector-init( n, fn (_) default ), -1, n, n)
I'm just saying that if I add 10 items to the queue, and then remove 10 items from the queue, this will no longer be `-1`. So is there a better number that keeps the invariant you want, but doesn't make the initial empty queue more special than a regular empty queue. For example does `n` or `n + 1` or something similar work? What does an empty queue look like versus a full queue, and what should the invariant be in both cases? And then make sure the initial queue holds to that invariant the same as your adding and removing functions and not some other equivalent invariant. I think that will make it easier to maintain and document.

2024-04-22 21:25 UTC, Ki11erRabbit commented on std/data/deque.kk
> +  Deque( vector-init( n, fn (_) default ), -1, n, n)
I just changed it to `n - 1`.

2024-04-22 21:50 UTC, TimWhiting requested changes

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +      Deque( new-data, front-idx = -1 % new-data.length, back-idx = new-size, size = new-size )
Let's make this the same as the other to be clear.

```suggestion
      Deque( new-data, front-idx = new-data.length - 1, back-idx = new-size, size = new-size )
```

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +  if index < 0 || index > d.size then
Indicies are one fewer than sizes right?

```suggestion
  if index < 0 || index >= d.size then
```

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +        match data.at( index )
We could make this a bit more efficient by using an unsafe api, because we know that the size is not zero in this case so there should be something at the calculated index. (And in `pop-back`)

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +        for(size) fn (i)
We should copy and make `forz` public from `std/core/vector`:
```koka
// Executes `action` `n` times for each integer between [`0`,`n`)  (excluding `n` ).
// If `n <= 0`  the function returns without any call to `action` .
fun forz( n : ssize_t, action : (ssize_t) -> e () ) : e ()
  fun rep( i : ssize_t )
    if i < n then
      action(i)
      rep(pretend-decreasing(i.incr))
  rep(0.ssize_t)
```

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +  val new-data = unsafe-vector( d.data.length.ssize_t )
Unsafe apis are not safe in the presence of vectors. Due to exceptions, or multiple resumptions, the vector could be at weird states of initialization. Use safe vector apis.

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +    match d.at( i )
It would be best to use unsafe apis for efficiency when we know the index is going to be valid.

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +      match (xs.at(i), ys.at(i))
Again with the efficiency, just use the unsafe api directly.

2024-04-22 21:50 UTC, TimWhiting commented on std/data/deque.kk
> +      match (xs.at(i), ys.at(i))
The goal of this PR is to provide an externally safe api, but feel free to use unsafe internally for accessing apis even in the presence of effects. On the otherhand make sure to avoid mutating apis in the presence of effects.

2024-04-22 21:51 UTC, TimWhiting requested changes
Had a few minutes to take a bit closer look at this. Here are a few comments.

2024-04-22 21:55 UTC, Ki11erRabbit commented
> Had a few minutes to take a bit closer look at this. Here are a few comments.

I'll will change the API and add in an `unsafe-deque-idx` function that will contain the logic for interacting with deque's ring buffer. That should fix most of the issues.

2024-04-23 01:11 UTC, TimWhiting approved these changes

2024-04-23 01:11 UTC, merged